# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Georgian Morphological Dictionary (Demo)
description: >
  The demo site for the Georgian Morphological Dictionary project.
  Frustrated by Georgian verbs? Or want to support the digitalization of
  the rich Georgian language? Read more about our project here and support
  our efforts!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: Asia/Tbilisi
permalink: /:categories/:title
gems:
  - octopress-debugger

# Build settings
markdown: kramdown
